import os
import re

def read_schema(schema_path):
    '''
    Reads the schema file and returns it as a single string.

    Inputs:
        * schema_path (str): Path to the schema file.

    Returns:
        * schema_text (str): Full schema text.
    '''
    with open(schema_path, "r") as file:
        schema_text = file.read()
    return schema_text

def extract_sql_query(response):
    '''
    Extracts the SQL query from the model's response.

    Inputs:
        * response (str): Raw text generated by the model.

    Returns:
        * sql_query (str): Extracted SQL query.
    '''
    response = response.strip()
    
    # Can't expect model will consistnely format SQL output
    # Try to start from the first SELECT
    select_position = response.upper().find("SELECT")
    return response[select_position:]

def save_logs(output_path, sql_em, record_em, record_f1, error_msgs):
    '''
    Save the logs of the experiment to files.
    You can change the format as needed.
    '''
    with open(output_path, "w") as f:
        f.write(f"SQL EM: {sql_em}\nRecord EM: {record_em}\nRecord F1: {record_f1}\nModel Error Messages: {error_msgs}\n")